# Generated by Django 5.1.7 on 2025-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('noida', 'Noida'), ('mumbai', 'Mumbai'), ('bangalore', 'Bangalore')], default='noida', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('government', 'Government Official'), ('admin', 'Administrator')], default='citizen', max_length=20),
        ),
    ]
